In [1]:
import torch
from torch import nn
from torch.nn import functional as F

## Loading and Saving Tensors

In [3]:
x = torch.arange(4)
torch.save(x, 'data/x-file')

In [4]:
# reading the file back
x2 = torch.load('data/x-file')
print(x2)

tensor([0, 1, 2, 3])


In [5]:
# storing a list of tensors
y = torch.zeros(4)
torch.save([x, y], 'data/x-files')
x2, y2 = torch.load('data/x-files')
print(x2, y2)

tensor([0, 1, 2, 3]) tensor([0., 0., 0., 0.])


## Loading and saving model parameters

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.output = nn.LazyLinear(10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [8]:
# saving and loading the whole model
torch.save(net.state_dict(), 'data/mlp.params')

In [10]:
# recovering the model
clone = MLP()
clone.load_state_dict(torch.load('data/mlp.params'))
clone.eval()

MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)

In [11]:
Y_clone = clone(X)
print(Y_clone == Y)
# the result is the same as both instances of the model have the same parameters

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])
